FROM python:3.11.8-slim-bullseye

EXPOSE 5000

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY app/ ./

CMD ["streamlit", "run", "app.py", "--server.port=5000", "--server.address=0.0.0.0"]
